src/discordtipbot/discordbot.cr
I have cleaned up the old PR with the same grammatical fixes as before, but also some extras with the responses to the user when there are errors. Most error messages use the same format now `**ERROR**: [some problem here]` and the bot is more consistent. I also added a message telling the user to visit support (using the `~support` command invite) if they see a recurring issue.
This fixes #9 too.
=> Grammatical fixes and response improvements

src/discordtipbot/discordbot.cr
I think I know how to use Git now!
This should be the same feature as before but a much nicer commit history.
=> Added 'amount each' to both ~soak and ~rain commands

sample-config.json
This JSON file had a bunch of extra whitespace and was invalid JSON; a line was missing a comma.
=> Fix invalid sample-config.json

src/discordtipbot/discordbot.cr
All error messages should now follow the same format.
=> Improve some response messages to follow the same format

src/discordtipbot/discordbot.cr
Formatting and functionality can be broadened later on.
=> add checkconfig

sample-config.json, src/discordtipbot/config.cr, src/discordtipbot/discordbot.cr, src/discordtipbot/tipbot.cr
(Somehow I forgot to switch branches)
=> implement balance warning

src/discordtipbot/discordbot.cr
I hope I removed all obsolete return's now
=> Remove obsolete return's

src/discordtipbot/discordbot.cr
=> Add missing return

src/discordtipbot/discordbot.cr
Somehow I wasn't paying attention rly, and accidentally merged changes that break on none latest crystal
=> Revert crystal master changes that got merged

src/discordtipbot/discordbot.cr, src/discordtipbot/tipbot.cr
I realized yesterday, that I'm actually not calculating the unclaimed coins, like I wanted to...
=> Fix unclaimed

src/discordtipbot/discordbot.cr
It's always a good idea to rely on as little third party as possible.
=> Switch to own domain for invites instead of discord.me

src/discordtipbot/discordbot.cr
Was previously broken if more then 1 user active
=> Fix ~lucky

src/discordtipbot/discordbot.cr
=> Grammatical improvements

src/discordtipbot/discordbot.cr
Not sure if this is the final text I want to use, but this will do for now.
Closes #44
=> Make use of the status to display info

src/discordtipbot/discordbot.cr
=> allow messages to be triggered without prefix in DMs

README.md, src/core_extensions/big_decimal.cr, src/core_extensions/json_bd.cr, src/discordtipbot.cr
=> Monkey patch BigDecimal to remove requirement for patched crystal

.travis.yml
(Only doing this via PR, to make sure the specs actually run and work)
=> Reenable spec'ing on Travis

src/discordtipbot/discordbot.cr
=> Improve amount parsing

src/discordtipbot/discordbot.cr
@z64 I think this is what you suggested in #52
=> Switch to guild streaming

src/discordtipbot/discordbot.cr
This commit converts the amount_each for !soak and !rain commands to BigDecimals so they can be rounded to 8 decimals and formatted correctly.
Resolves #54
=> Fix rounding issues with !soak and !rain

src/discordtipbot/discordbot.cr, src/discordtipbot/presence_cache.cr
=> Track User Presences (Fixes soak)

schema.sql, src/discordtipbot.cr, src/discordtipbot/discordbot.cr, src/discordtipbot/statistics.cr, src/discordtipbot/tipbot.cr, statistics_materialized_view.sql
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/greenbigfrog/discordtipbot/82)
=> Add in detail statistics

offsite.sql, sample-config.json, schema.sql, shard.lock, src/discordtipbot/coin_api.cr, src/discordtipbot/config.cr, src/discordtipbot/discordbot.cr, src/discordtipbot/enums.cr, src/discordtipbot/tipbot.cr
=> Offsite coins storage

src/discordtipbot/discordbot.cr
The new GitHub command links users to the GitHub repository to contribute to development.
Closes #97.
=> Add github command

src/discordtipbot/crystal/string.cr, src/discordtipbot/discordbot.cr, src/launcher.cr
Implements what was started in #100 in a better way.
Thanks to @IncognitoJam for originally opening the PR.
=> Ignore multiple whitespaces in command handling
